apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-mysql-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0a695e8482f0a4bab  # Update with the correct Volume ID
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-wordpress-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-04bf262ea209845f4
